apiVersion: v1
name: isidro
version: 0.1.0
dependencies:
- name: rabbitmq
  version: 8.30.2
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
- name: mongodb
  version: 11.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
- name: redis
  version: 16.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled