title: "Isidro Provisioner"
description: "Role for automated Terraform provisioning of Isidro chatbot systems"
stage: Beta
includedPermissions:
- binaryauthorization.attestors.create
- binaryauthorization.attestors.delete
- binaryauthorization.attestors.get
- binaryauthorization.attestors.update
- binaryauthorization.policy.get
- binaryauthorization.policy.update
- cloudkms.cryptoKeyVersions.create
- cloudkms.cryptoKeyVersions.destroy
- cloudkms.cryptoKeyVersions.get
- cloudkms.cryptoKeyVersions.list
- cloudkms.cryptoKeyVersions.restore
- cloudkms.cryptoKeyVersions.update
- cloudkms.cryptoKeyVersions.viewPublicKey
- cloudkms.cryptoKeys.create
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.cryptoKeys.update
- cloudkms.keyRings.create
- cloudkms.keyRings.get
- compute.instanceGroupManagers.get
- compute.zones.list
- container.clusters.create
- container.clusters.delete
- container.clusters.get
- container.clusters.update
- container.configMaps.create
- container.configMaps.delete
- container.configMaps.get
- container.namespaces.create
- container.namespaces.delete
- container.namespaces.get
- container.operations.get
- containeranalysis.notes.create
- containeranalysis.notes.delete
- containeranalysis.notes.get
- gkehub.memberships.create
- gkehub.memberships.delete
- gkehub.memberships.get
- gkehub.operations.get
- iam.serviceAccountKeys.create
- iam.serviceAccountKeys.get
- iam.serviceAccounts.create
- iam.serviceAccounts.delete
- iam.serviceAccounts.actAs
- iam.serviceAccounts.get
- iam.serviceAccounts.list
- iam.serviceAccounts.update
- monitoring.alertPolicies.create
- monitoring.alertPolicies.delete
- monitoring.alertPolicies.get
- monitoring.alertPolicies.update
- monitoring.slos.create
- monitoring.slos.delete
- monitoring.slos.get
- serviceusage.services.disable
- serviceusage.services.enable
- serviceusage.services.get
- serviceusage.services.list
- resourcemanager.projects.get
- resourcemanager.projects.getIamPolicy
- resourcemanager.projects.setIamPolicy