title: "Isidro Provisioner"
description: "Role for automated Terraform provisioning of Isidro chatbot systems"
stage: Beta
includedPermissions:
- binaryauthorization.attestors.create
- binaryauthorization.attestors.delete
- binaryauthorization.attestors.get
- binaryauthorization.attestors.update
- binaryauthorization.policy.get
- binaryauthorization.policy.update
- cloudkms.cryptoKeyVersions.create
- cloudkms.cryptoKeyVersions.destroy
- cloudkms.cryptoKeyVersions.get
- cloudkms.cryptoKeyVersions.list
- cloudkms.cryptoKeyVersions.restore
- cloudkms.cryptoKeyVersions.update
- cloudkms.cryptoKeyVersions.viewPublicKey
- cloudkms.cryptoKeys.create
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.cryptoKeys.update
- cloudkms.keyRings.create
- cloudkms.keyRings.get
- compute.globalAddresses.create
- compute.globalAddresses.delete
- compute.globalAddresses.get
- compute.instanceGroupManagers.get
- compute.networks.create
- compute.networks.delete
- compute.networks.get
- compute.networks.updatePolicy
- compute.subnetworks.create
- compute.subnetworks.delete
- compute.subnetworks.get
- compute.subnetworks.setPrivateIpGoogleAccess
- compute.zones.list
- container.clusters.create
- container.clusters.delete
- container.clusters.get
- container.clusters.update
- container.configMaps.create
- container.configMaps.delete
- container.configMaps.get
- container.customResourceDefinitions.list
- container.namespaces.create
- container.namespaces.delete
- container.namespaces.get
- container.operations.get
- container.thirdPartyObjects.create
- container.thirdPartyObjects.delete
- container.thirdPartyObjects.get
- container.thirdPartyObjects.update
- containeranalysis.notes.create
- containeranalysis.notes.delete
- containeranalysis.notes.get
- dns.changes.create
- dns.changes.get
- dns.changes.list
- dns.managedZoneOperations.get
- dns.managedZoneOperations.list
- dns.managedZones.create
- dns.managedZones.delete
- dns.managedZones.get
- dns.managedZones.list
- dns.managedZones.update
- dns.networks.bindPrivateDNSZone
- dns.resourceRecordSets.create
- dns.resourceRecordSets.delete
- dns.resourceRecordSets.get
- dns.resourceRecordSets.list
- dns.resourceRecordSets.update
- gkehub.features.create
- gkehub.features.delete
- gkehub.features.get
- gkehub.memberships.create
- gkehub.memberships.delete
- gkehub.memberships.get
- gkehub.operations.get
- iam.serviceAccountKeys.create
- iam.serviceAccountKeys.get
- iam.serviceAccounts.create
- iam.serviceAccounts.delete
- iam.serviceAccounts.actAs
- iam.serviceAccounts.get
- iam.serviceAccounts.list
- iam.serviceAccounts.update
- monitoring.alertPolicies.create
- monitoring.alertPolicies.delete
- monitoring.alertPolicies.get
- monitoring.alertPolicies.update
- monitoring.slos.create
- monitoring.slos.delete
- monitoring.slos.get
- serviceusage.services.disable
- serviceusage.services.enable
- serviceusage.services.get
- serviceusage.services.list
- spanner.databases.create
- spanner.databases.drop
- spanner.databases.get
- spanner.databaseOperations.get
- spanner.instances.create
- spanner.instances.delete
- spanner.instances.get
- spanner.instanceOperations.get
- redis.instances.create
- redis.instances.delete
- redis.instances.get
- redis.operations.get
- resourcemanager.projects.get
- resourcemanager.projects.getIamPolicy
- resourcemanager.projects.setIamPolicy