{{ if eq .Values.keywords.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: keywords
  labels:
    app: keywords
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: keywords
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keywords
  labels:
    app: keywords
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keywords
  template:
    metadata:
      labels:
        app: keywords
        sidecar.istio.io/inject: "true"
        istio.io/rev: "asm-managed"
    spec:
      serviceAccountName: tracing-microservice
      containers:
      - name: keywords
        image: {{ .Values.keywords.image.repository }}:{{ .Values.keywords.image.tag }}
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keywords
spec:
  podSelector:
    matchLabels:
      app: keywords
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: orchestration
  egress:
  - {}
{{ end }}