---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracing-microservice
  annotations:
    iam.gke.io/gcp-service-account: isidro-tracing-microservices@{{ .Values.project }}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-client-microservice
  annotations:
    iam.gke.io/gcp-service-account: isidro-db-client-microservices@{{ .Values.project }}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubebash-microservice
  annotations:
    iam.gke.io/gcp-service-account: isidro-kubebash-microservices@{{ .Values.project }}.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebash-execution
subjects:
- kind: ServiceAccount
  name: kubebash-microservice
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io